package by.epamtc.utilities.controller.command;

public enum CommandName {
	GO_TO_MAIN_PAGE,
	GO_TO_AUTH_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_CABINET_PAGE,
	AUTH,
	REGISTRATION,
	CHANGE_LANGUAGE,
	PROFILE,
	LOGOUT,
	CHANGE_PROFILE,
	GO_TO_ADMIN_REGISTRATION,
	ADMIN_REGISTRATION,
	GO_TO_ADMIN_LIST_PAGE,
	GO_TO_ORDERS_PAGE
}
