package by.epamtc.utilities.controller.command;

public enum CommandName {
	GO_TO_MAIN_PAGE,
	GO_TO_AUTH_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_CABINET_PAGE,
	AUTH,
	REGISTRATION,
	CHANGE_LANGUAGE,
	PROFILE,
	LOGOUT,
	CHANGE_PROFILE,
	GO_TO_ADMIN_REGISTRATION,
	ADMIN_REGISTRATION,
	GO_TO_ADMIN_LIST_PAGE,
	GO_TO_ORDERS_PAGE,
	GO_TO_CREATE_ORDER_PAGE,
	CREATE_ORDER,
	GO_TO_CREATE_NOTE_PAGE,
	CREATE_NOTE,
	GO_TO_EMPLOYEES_PAGE,
	GO_TO_WORK_PLAN_LIST_PAGE
}
